dir = File.expand_path(File.dirname(__FILE__))

path = dir + "/FalaComMeuCarro/Models/IPAddress.swift"
ip_address = `ipconfig getifaddr en0`.gsub("\n", "")

swift_define =<<-EOF
//This file is autogenerated by ip_address.rb
let SERVER_IP = "#{ip_address}"
EOF

File.open(path, 'w+') do |f|
	f.write swift_define
end
